#!/bin/bash -e
. "$(dirname "$0")"/../common.sh

bazel build :TestBinary_deploy.jar

! unzip -v | grep -q Debian || diff expected  <( \
  unzip -l "$(bazel info bazel-bin)/deployjar/TestBinary_deploy.jar" \
  | tail -n+2 \
)
