#!/bin/bash -e
. "$(dirname "$0")"/../common.sh

bazel build :TestBinary_deploy.jar

diff <(sort expected) <(
    zipinfo -m -T --h-t "$(bazel info bazel-bin)/deployjar/TestBinary_deploy.jar" | sort
)
