#!/bin/bash -e
. "$(dirname "$0")"/../common.sh

[[ "$(bazel version | head -n1 | cut -d: -f2 | tr -d ' ')" =~ 0.15.*|0.16.* ]] || bazel build :zero_scala_proto
# todo: fix me!
# bazel build :zero_scala
