load("//rules:build.bzl", "annex_scala_library")

scala = [
    "@scalas//:scala_2_11_0",
]

annex_scala_library(
    name = "library",
    srcs = ["code.scala"],
    scala = scala,
    tags = ["manual"],
)
