load("@rules_scala_annex//rules/scala:compat.bzl", "annex_scala_library")

scala = "@scala_2_11"

annex_scala_library(
    name = "library",
    srcs = ["code.scala"],
    scala = scala,
    tags = ["manual"],
)
