load("@rules_scala_annex//rules:build.bzl", "annex_scala_format_test")

annex_scala_format_test(
    name = "formatted",
    srcs = ["formatted.scala"],
)

annex_scala_format_test(
    name = "unformatted",
    srcs = ["unformatted.scala"],
)
