#!/bin/bash -e
. "$(dirname "$0")"/../../common.sh

# scala_format_test
## check
bazel test :formatted
! bazel test :unformatted
## copy
cp unformatted.template.scala unformatted.tmp.scala
! bazel test :unformatted-copy 
bazel run :unformatted-copy
bazel test :unformatted-copy
rm unformatted.tmp.scala

# non-default output format test: binary
## check
bazel run :formatted-binary.format-test
! bazel run :unformatted-binary.format-test
## copy
cp unformatted.template.scala unformatted.tmp.scala
! bazel run :unformatted-binary-copy.format-test
bazel run :unformatted-binary-copy.format
bazel run :unformatted-binary-copy.format-test
rm unformatted.tmp.scala

# non-default output format test: library
## check
bazel run :formatted-library.format-test
! bazel run :unformatted-library.format-test
## copy
cp unformatted.template.scala unformatted.tmp.scala
! bazel run :unformatted-library-copy.format-test
bazel run :unformatted-library-copy.format
bazel run :unformatted-library-copy.format-test
rm unformatted.tmp.scala

# non-default output format test: test
## check
bazel run :formatted-test.format-test
! bazel run :unformatted-test.format-test
## copy
cp unformatted.template.scala unformatted.tmp.scala
! bazel run :unformatted-test-copy.format-test
bazel run :unformatted-test-copy.format
bazel run :unformatted-test-copy.format-test
rm unformatted.tmp.scala
