#!/bin/bash -e
#. "$(dirname "$0")"/../../common.sh

#zip example.srcjar Example.scala
#bazel build :lib
#diff expected  <(
#    zipinfo -m -T --h-t "$(bazel info bazel-bin)/compile/srcjar/lib.jar"
#)
