#!/bin/bash -e
. "$(dirname "$0")"/../../common.sh

zip example.srcjar Example.scala
bazel build :lib
diff expected  <( \
  unzip -l "$(bazel info bazel-bin)/compile/srcjar/lib.jar" \
  | tail -n+2 \
  | sed 's/\([0-9]\{2\}\)-\([0-9]\{2\}\)-\([0-9]\{4\}\)/\3-\1-\2/' \
)
