#!/bin/bash -e
. "$(dirname "$0")"/../../common.sh

zip example.srcjar Example.scala
bazel build :lib
! unzip -v | grep -q Debian || diff expected  <( \
  unzip -l "$(bazel info bazel-bin)/compile/srcjar/lib.jar" \
  | tail -n+2 \
)
