load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
load("@bazel_tools//tools/build_defs/repo:jvm.bzl", "jvm_maven_import_external")

http_archive(
    name = "bazel_skylib",
    sha256 = "c0289fef5237c31e8462042b4cc3bdf831a3d3d135bb4a0d493a5072acecb074",
    strip_prefix = "bazel-skylib-2169ae1c374aab4a09aa90e65efe1a3aad4e279b",
    urls = ["https://github.com/bazelbuild/bazel-skylib/archive/2169ae1c374aab4a09aa90e65efe1a3aad4e279b.zip"],
)

http_archive(
    name = "com_google_protobuf",
    sha256 = "2c8f8614fb1be709d68abaab6b4791682aa7db2048012dd4642d3a50b4f67cb3",
    strip_prefix = "protobuf-0038ff49af882463c2af9049356eed7df45c3e8e",
    urls = ["https://github.com/google/protobuf/archive/0038ff49af882463c2af9049356eed7df45c3e8e.zip"],
)

local_repository(
    name = "rules_scala_annex",
    path = "../",
)

load(
    "@rules_scala_annex//rules/scala:workspace.bzl",
    "scala_register_toolchains",
    "scala_repositories",
)

scala_repositories()

scala_register_toolchains()

load(
    "@rules_scala_annex//rules/scala_proto:workspace.bzl",
    "scala_proto_register_toolchains",
    "scala_proto_repositories",
)

scala_proto_repositories()

scala_proto_register_toolchains()

load("@rules_scala_annex//rules:rules_scala.bzl", "emulate_rules_scala")
load("@rules_scala_annex//rules:external.bzl", "scala_import_external")

scala_import_external(
    name = "scalatest_2_11",
    jar_sha256 = "f198967436a5e7a69cfd182902adcfbcb9f2e41b349e1a5c8881a2407f615962",
    jar_urls = ["https://mirror.bazel.build/oss.sonatype.org/content/groups/public/org/scalatest/scalatest_2.11/2.2.6/scalatest_2.11-2.2.6.jar"],
    licenses = ["notice"],
)

emulate_rules_scala(
    extra_deps = [
        "@scala_reflect_2_11_12//jar",
        "@org_scala_lang_modules_scala_xml_2_11//jar",
    ],
    scala = "//scala:2_11",
    scalatest = "@scalatest_2_11//jar",
)

load("@rules_scala_annex//rules/scalafmt:workspace.bzl", "scalafmt_default_config", "scalafmt_repositories")

scalafmt_repositories()

scalafmt_default_config()

load(":workspace.bzl", "maven_dependencies")

maven_dependencies()

jvm_maven_import_external(
    name = "kind_projector_2_11",
    artifact = "org.spire-math:kind-projector_2.12:0.9.6",
    licenses = ["notice"],
    server_urls = ["http://central.maven.org/maven2"],
)

jvm_maven_import_external(
    name = "kind_projector_2_12",
    artifact = "org.spire-math:kind-projector_2.12:0.9.6",
    licenses = ["notice"],
    server_urls = ["http://central.maven.org/maven2"],
)

jvm_maven_import_external(
    name = "org_scalacheck_scalacheck_2_11",
    artifact = "org.scalacheck:scalacheck_2.11:1.14.0",
    licenses = ["notice"],
    server_urls = ["http://central.maven.org/maven2"],
)

jvm_maven_import_external(
    name = "junit",
    artifact = "junit:junit:4.12",
    licenses = ["notice"],
    server_urls = ["http://central.maven.org/maven2"],
)

jvm_maven_import_external(
    name = "hamcrest_core",
    artifact = "org.hamcrest:hamcrest-core:1.3",
    licenses = ["notice"],
    server_urls = ["http://central.maven.org/maven2"],
)

jvm_maven_import_external(
    name = "junit_interface",
    artifact = "com.novocode:junit-interface:jar:0.11",
    licenses = ["notice"],
    server_urls = ["http://central.maven.org/maven2"],
)

jvm_maven_import_external(
    name = "scala_compiler_2_11_12",
    artifact = "org.scala-lang:scala-compiler:2.11.12",
    licenses = ["notice"],
    server_urls = ["http://central.maven.org/maven2"],
)

jvm_maven_import_external(
    name = "scala_library_2_11_12",
    artifact = "org.scala-lang:scala-library:2.11.12",
    licenses = ["notice"],
    server_urls = ["http://central.maven.org/maven2"],
)

jvm_maven_import_external(
    name = "scala_reflect_2_11_12",
    artifact = "org.scala-lang:scala-reflect:2.11.12",
    licenses = ["notice"],
    server_urls = ["http://central.maven.org/maven2"],
)

jvm_maven_import_external(
    name = "scala_compiler_2_12_6",
    artifact = "org.scala-lang:scala-compiler:2.12.6",
    licenses = ["notice"],
    server_urls = ["http://central.maven.org/maven2"],
)

jvm_maven_import_external(
    name = "scala_library_2_12_6",
    artifact = "org.scala-lang:scala-library:2.12.6",
    licenses = ["notice"],
    server_urls = ["http://central.maven.org/maven2"],
)

jvm_maven_import_external(
    name = "scala_reflect_2_12_6",
    artifact = "org.scala-lang:scala-reflect:2.12.6",
    licenses = ["notice"],
    server_urls = ["http://central.maven.org/maven2"],
)

jvm_maven_import_external(
    name = "scala_compiler_typelevel_2_12_1",
    artifact = "org.typelevel:scala-compiler:2.12.1",
    licenses = ["notice"],
    server_urls = ["http://central.maven.org/maven2"],
)

jvm_maven_import_external(
    name = "scala_library_typelevel_2_12_1",
    artifact = "org.typelevel:scala-library:2.12.1",
    licenses = ["notice"],
    server_urls = ["http://central.maven.org/maven2"],
)

jvm_maven_import_external(
    name = "scala_reflect_typelevel_2_12_1",
    artifact = "org.typelevel:scala-reflect:2.12.1",
    licenses = ["notice"],
    server_urls = ["http://central.maven.org/maven2"],
)

bind(
    name = "default_scala",
    actual = "//scala:zinc_typelevel_2_12_1",
)
