load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "com_google_protobuf",
    sha256 = "7404d040865a031e80c2810cd9453eafefb2bbbf5f5f9a282b1d071d8e12c4bf",
    strip_prefix = "protobuf-3.5.2",
    urls = ["https://github.com/google/protobuf/archive/v3.5.2.zip"],
)

local_repository(
    name = "rules_scala_annex",
    path = "../",
)

load(
    "@rules_scala_annex//rules/scala:workspace.bzl",
    "annex_scala_register_toolchains",
    "annex_scala_repository",
    "annex_scala_repositories",
)

annex_scala_repositories()

annex_scala_register_toolchains()

annex_scala_repository(
    "scala_2_11",
    ("org.scala-lang", "2.11.11"),
    "@compiler_bridge_2_11//:src",
)

annex_scala_repository(
    "scala_2_12",
    ("org.scala-lang", "2.12.4"),
    "@compiler_bridge_2_12//:src",
)

annex_scala_repository(
    "typelevel_2_12",
    ("org.typelevel", "2.12.1"),
    "@compiler_bridge_2_12//:src",
)

annex_scala_repository(
    "scala",
    ("org.typelevel", "2.12.1"),
    "@compiler_bridge_2_12//:src",
)

load("@rules_scala_annex//rules:rules_scala.bzl", "emulate_rules_scala")
load("@rules_scala_annex//rules:external.bzl", "scala_import_external")

scala_import_external(
    name = "scalatest_2_11",
    jar_sha256 = "f198967436a5e7a69cfd182902adcfbcb9f2e41b349e1a5c8881a2407f615962",
    jar_urls = ["https://mirror.bazel.build/oss.sonatype.org/content/groups/public/org/scalatest/scalatest_2.11/2.2.6/scalatest_2.11-2.2.6.jar"],
    licenses = ["notice"],
)

emulate_rules_scala(
    extra_deps = ["@scala_2_11_scala_reflect//jar"],
    scala = "@scala_2_11",
    scalatest = "@scalatest_2_11//jar",
)

load("@rules_scala_annex//rules/scalafmt:workspace.bzl", "annex_scalafmt_repositories", "scalafmt_default_config")

annex_scalafmt_repositories()

scalafmt_default_config()

load("//3rdparty:workspace.bzl", "maven_dependencies")

maven_dependencies()

maven_jar(
    name = "kind_projector_2_11",
    artifact = "org.spire-math:kind-projector_2.12:0.9.6",
)

maven_jar(
    name = "kind_projector_2_12",
    artifact = "org.spire-math:kind-projector_2.12:0.9.6",
)

maven_jar(
    name = "org_scalacheck_scalacheck_2_11",
    artifact = "org.scalacheck:scalacheck_2.11:1.14.0",
)

# see rules_docker directory

git_repository(
    name = "io_bazel_rules_docker",
    remote = "https://github.com/bazelbuild/rules_docker.git",
    tag = "v0.4.0",
)

rules_docker_version = "452878d665648ada0aaf816931611fdd9c683a97"

http_archive(
    name = "io_bazel_rules_docker",
    strip_prefix = "rules_docker-%s" % rules_docker_version,
    type = "zip",
    url = "https://github.com/bazelbuild/rules_docker/archive/%s.zip" % rules_docker_version,
)

load(
    "@io_bazel_rules_docker//scala:image.bzl",
    _scala_image_repos = "repositories",
)

_scala_image_repos()

# intellij

maven_jar(
    name = "truth",
    artifact = "com.google.truth:truth:0.30",
    sha1 = "9d591b5a66eda81f0b88cf1c748ab8853d99b18b",
)

maven_jar(
    name = "junit",
    artifact = "junit:junit:4.12",
    sha1 = "2973d150c0dc1fefe998f834810d68f278ea58ec",
)

http_archive(
    name = "com_google_protobuf",
    strip_prefix = "protobuf-master",
    urls = ["https://github.com/google/protobuf/archive/master.zip"],
)

http_archive(
    name = "com_google_protobuf_java",
    strip_prefix = "protobuf-master",
    urls = ["https://github.com/google/protobuf/archive/master.zip"],
)

new_http_archive(
    name = "intellij_ce_2017_3",
    build_file = "@intellij_with_bazel//:intellij_platform_sdk/BUILD.idea",
    sha256 = "fcc571a869808776c7e336e301246e2db0f6adcbfaf7244422cb97f8be0e06d1",
    url = "https://www.jetbrains.com/intellij-repository/releases/com/jetbrains/intellij/idea/ideaIC/2017.3.5/ideaIC-2017.3.5.zip",
)

maven_jar(
    name = "error_prone_annotations",
    artifact = "com.google.errorprone:error_prone_annotations:2.3.0",
    sha1 = "dc72efd247e1c8489df04af8a5451237698e6380",
)

intellij_version = "2dbee06790bbb05a70d519d6d1ef20f32abb06d7"

http_archive(
    name = "intellij_with_bazel",
    strip_prefix = "intellij-%s" % intellij_version,
    type = "zip",
    url = "https://github.com/bazelbuild/intellij/archive/%s.zip" % intellij_version,
)
