#!/bin/bash -e
. "$(dirname "$0")"/../../common.sh

bazel build :plain
! unzip -v | grep -q Debian || diff expected  <( \
   unzip -l "$(bazel info bazel-bin)/resources/plain/plain.jar" \
   | tail -n+2 \
)


bazel build :merged
! unzip -v | grep -q Debian || diff expected_merged  <( \
    unzip -l "$(bazel info bazel-bin)/resources/plain/merged.jar" \
    | tail -n+2 \
)
