#!/bin/bash -e
. "$(dirname "$0")"/../../common.sh

bazel build :plain
diff expected_plain <(
    zipinfo -m -T --h-t "$(bazel info bazel-bin)/resources/plain/plain.jar"
)

bazel build :merged
diff expected_merged <(
    zipinfo -m -T --h-t "$(bazel info bazel-bin)/resources/plain/merged.jar"
)
