#!/bin/bash -e
. "$(dirname "$0")"/../../common.sh

! bazel build :bad_compile
bazel build :bad_compile |& grep 'You may be missing a `macro = True` attribute.'
[ "$(bazel run :test_macro)" = "hello world!" ]
[ "$(bazel run :test_macro_only)" = $'hello world!\nworld hello!' ]
