#!/bin/bash -e
. "$(dirname "$0")"/../../common.sh

bazel build :0_used
! bazel build :0_unused || false
bazel build :0_unused | grep "buildozer 'remove deps @annex_test//:org_scalacheck_scalacheck_2_12_1_13_4' //dependencies/unused:0_unused"
bazel build :indirect_unused
