#!/bin/bash -e
. "$(dirname "$0")"/../../common.sh

# Using a worker here prevents a println this tests needs from making it
# to the command line, so we use standalone instead.
bazel build :inefficient-usage --strategy=ScalaCompile=standalone 2>&1 | \
  awk '
      BEGIN                           {z  = 2}
      /slightly inefficient/          {z -= 1}
      /scalac plugin phase success/   {z -= 1}
      END                             {exit z}'
