#!/bin/bash -e
. "$(dirname "$0")"/../../common.sh

echo "class A$RANDOM" > Example.gen.scala

rm -fr "$(bazel info execution_root)/.bazel-zinc"
bazel build --noworker_sandboxing --worker_extra_flag=ScalaCompile=--persistence_dir=.bazel-zinc :lib
[ "$(unzip -l "$(bazel info execution_root)/.bazel-zinc/compile/zinc_inc_lib/classes.jar" | grep '\.class' | wc -l | xargs echo)" = 1 ]
