#!/bin/bash -e
. "$(dirname "$0")"/../../common.sh

bazel build :prefix
diff expected <(
    zipinfo -m -T --h-t "$(bazel info bazel-bin)/resources/prefix/prefix.jar"
)

! bazel build :outside
bazel build :outside |& grep 'does not have prefix'
