#!/bin/bash -e
. "$(dirname "$0")"/../../common.sh

bazel build :prefix
diff expected  <( \
  unzip -l "$(bazel info bazel-bin)/resources/prefix/prefix.jar" \
  | tail -n+2 \
  | sed 's/\([0-9]\{2\}\)-\([0-9]\{2\}\)-\([0-9]\{4\}\)/\3-\1-\2/' \
)

! bazel build :outside
bazel build :outside |& grep 'does not have prefix'
