load("//rules:build.bzl", "annex_configure_scala_testing_frameworks")

annex_configure_scala_testing_frameworks(
    scalatest  = "org.scalatest.tools.Framework",
    scalacheck = "org.scalacheck.ScalaCheckFramework",
    specs2     = "org.specs2.runner.Specs2Framework",
    minitest   = "minitest.runner.Framework",
    utest      = "utest.runner.Framework",
)
