#!/bin/bash -e
. "$(dirname "$0")"/../../common.sh

bazel build :Runtime
bazel build :Exported
bazel build :ExportOnly
bazel build :OtherLib
bazel build :MacroTest
bazel build :OtherJavaLib
bazel build :HelloLib
bazel run :ScalaBinary
bazel test :HelloLibTest
bazel test :HelloLibTestSuite_test_suite_HelloLibTest.scala
bazel test :HelloLibTestSuite_test_suite_HelloLibTest2.scala
bazel test :HelloLibTestSuite
