#!/bin/bash -e
. "$(dirname "$0")"/../../common.sh

bazel build :maven
# note: date formats for unzip vary
diff expected  <( \
   unzip -l "$(bazel info bazel-bin)/resources/maven/maven.jar" \
   | tail -n+2 \
   | sed 's/\([0-9]\{2\}\)-\([0-9]\{2\}\)-\([0-9]\{4\}\)/\3-\1-\2/' \
)
