load("//rules:build.bzl", "annex_scala_library")

scala = [
    "@scalas//:scala_2_12_4",
]

annex_scala_library(
    name = "welcome_to_bloop",
    srcs = ["welcome_to_bloop.scala"],
    scala = scala,
    tags = ["manual"],
)
