load("@rules_scala_annex//rules:scala.bzl", "scala_library")

scala = "@scala_2_12"

scala_library(
    name = "welcome_to_bloop",
    srcs = ["welcome_to_bloop.scala"],
    scala = scala,
    tags = ["manual"],
)
