#!/bin/bash -e
. "$(dirname "$0")"/../../common.sh

out_2_13=$(bazel test :mixed_2_13)
echo "$out_2_13" | grep 'have size 0'
echo "$out_2_13" | grep 'JUnit many success'

bazel test :mixed_2_12 | grep 'Dummy.bar: OK, proved property.'
bazel test :mixed_2_12 --test_arg=--verbosity=HIGH | grep 'org.scalacheck.ScalaCheckFramework: 1 tests'
bazel test :mixed_2_12 --test_arg=--verbosity=MEDIUM | grep -v 'org.scalacheck.ScalaCheckFramework: 1 tests'
