load(":phases/api.bzl", "adjust_phases", "run_phases")
load(":phases/phase_bootstrap_compile.bzl", "phase_bootstrap_compile")
load(":phases/phase_classpaths.bzl", "phase_classpaths")
load(":phases/phase_coda.bzl", "phase_coda")
load(":phases/phase_ijinfo.bzl", "phase_ijinfo")
load(":phases/phase_noop.bzl", "phase_noop")
load(":phases/phase_resources.bzl", "phase_resources")
load(":phases/phase_zinc_compile.bzl", "phase_zinc_compile")
load(":phases/phase_zinc_depscheck.bzl", "phase_zinc_depscheck")
load(":phases/phase_javainfo.bzl", "phase_javainfo")
load(":phases/phase_library_defaultinfo.bzl", "phase_library_defaultinfo")
load(":phases/phase_singlejar.bzl", "phase_singlejar")
load(":phases/phase_binary_deployjar.bzl", "phase_binary_deployjar")
load(":phases/phase_binary_launcher.bzl", "phase_binary_launcher")
load(":phases/phase_scalafmt_nondefault_outputs.bzl", "phase_scalafmt_nondefault_outputs")
load(":phases/phase_test_launcher.bzl", "phase_test_launcher")
