load("//rules/common:private/utils.bzl", "safe_name", "strip_margin")

def annex_configure_scala_repository_implementation(ctx):
    build_contents = strip_margin("""
      |#
      |# generated by scala annex
      |#
      |
      |load("@rules_scala_annex//rules:scala.bzl", "annex_configure_scala")
      |
      |annex_configure_scala(
      |    name = '{name}',
      |    version = '{version}',
      |    compiler_classpath = [
      |        '@{name}_scala_compiler//jar',
      |        '@{name}_scala_reflect//jar',
      |        '@{name}_scala_library//jar',
      |    ],
      |    compiler_bridge = '{compiler_bridge}',
      |    compiler_bridge_classpath = [
      |        '@scala_annex_org_scala_sbt_compiler_interface//jar',
      |        '@scala_annex_org_scala_sbt_util_interface//jar',
      |    ],
      |    runtime_classpath = [
      |        '@{name}_scala_library//jar',
      |    ],
      |    visibility = ["//visibility:public"],
      |)
    """.format(
        version = ctx.attr.version,
        name = ctx.name,
        compiler_bridge = ctx.attr.compiler_bridge,
    ))

    ctx.file("BUILD", build_contents, False)
