#!/bin/bash -e

abs_path() {
    perl -MCwd -le '
    for (@ARGV) {
      if ($p = Cwd::abs_path $_) {
        print $p;
      } else {
        warn "abs_path: $_: $!\n";
        $ret = 1;
      }
    }
    exit $ret' "$@"
}
workspace=$(cd $(dirname "$0")/..; pwd)
root_workspace=$(cd $(dirname $(abs_path "$0"))/..; pwd)

default_bazel_version='3.1.0'

if [ -z "$BAZEL_VERSION" ]; then
    bazel_version="$default_bazel_version"
else
    bazel_version="$BAZEL_VERSION"
fi

case "$bazel_version" in
    'host')
        bazel_version=$("$BAZEL_REAL" version | awk '/Build label/ {print $3}' | cut -d '-' -f 1)
        bazel="$BAZEL_REAL"
        ;;
    '3.0.0')
        darwin_sha='c6109f211f932866ef86f6ed996b31910b3a74a8d5275d3d6a416dafe61c00c6'
        linux_sha='eb7aaa85d81c6d1caa5352e0573817217d0c364302aeee923a5cdb04f26d2bd3'
        ;;
    '3.1.0')
        darwin_sha='5cfa97031b43432b3c742c80e2e01c41c0acdca7ba1052fc8cf1e291271bc9cd'
        linux_sha='7ba815cbac712d061fe728fef958651512ff394b2708e89f79586ec93d1185ed'
        ;;
    *)
        echo "The requested Bazel version '$bazel_version' is not supported"
        exit 1
        ;;
esac

if [ -z "$bazel" ]; then
    bazel_bin_loc=~/.bazel_binaries
    mkdir -p $bazel_bin_loc
    bazel=$bazel_bin_loc/$bazel_version/bin/bazel-real
fi

if ! [ -f "$bazel" ]; then
    case $(uname -s) in
        Darwin)
            platform='darwin'
            sha=$darwin_sha
            ;;
        Linux)
            platform='linux'
            sha=$linux_sha
            ;;
        *)
            echo 'Your OS is not supported.'
            exit 1
            ;;
    esac
    remote_source=https://github.com/bazelbuild/bazel/releases/download
    installer_name="bazel-$bazel_version-installer-$platform-x86_64.sh"
    url="$remote_source/$bazel_version/$installer_name"
    (
        tmp_dir=$(mktemp -d)
        trap "rm -rf $tmp_dir" EXIT
        cd $tmp_dir
        (>&2 echo "downloading installer from")
        (>&2 echo "$url")
        curl -o installer.sh -L $url
        generated_sha=$(shasum -a 256 installer.sh | awk '{print $1}')
        if [ "$generated_sha" != "$sha" ]; then
            echo "Sha 256 does not match, expected: $sha"
            echo "But found $generated_sha"
            echo "Recommend you: update the sha to the expected"
            echo "and then re-run this script"
            exit 1
        fi
        chmod +x installer.sh
        ./installer.sh --base=$bazel_bin_loc/$bazel_version --bin=$bazel_bin_loc/$bazel_version/bin_t
    )
fi

extra_command_args=()

IFS=. read -r major minor patch < <(echo "$bazel_version")
extra_command_args+=("--config=v$major.$minor")

for (( i=1; i<=$#; i++ ))
do
    case "${!i}" in
        -*)
            ;;
        *)
            n=$(($i + 1))
            set -- "${@:1:$i}" "${extra_command_args[@]}" "${@:$n}"
            break
            ;;
    esac
done

disk_cache="$root_workspace"/.bazel_cache
mkdir -p "$disk_cache"

(>&2 echo :: exec "$bazel" "$@")
exec "$bazel" "$@"
