#!/bin/bash -e

abs_path() {
    perl -MCwd -le '
    for (@ARGV) {
      if ($p = Cwd::abs_path $_) {
        print $p;
      } else {
        warn "abs_path: $_: $!\n";
        $ret = 1;
      }
    }
    exit $ret' "$@"
}
workspace=$(cd $(dirname "$0")/..; pwd)
root_workspace=$(cd $(dirname $(abs_path "$0"))/..; pwd)

default_bazel_version='5.0.0'

if [ -z "$BAZEL_VERSION" ]; then
    bazel_version="$default_bazel_version"
else
    bazel_version="$BAZEL_VERSION"
fi

case "$bazel_version" in
    'host')
        bazel_version=$("$BAZEL_REAL" version | awk '/Build label/ {print $3}' | cut -d '-' -f 1)
        bazel="$BAZEL_REAL"
        ;;
    '4.1.0')
        darwin_sha='fddad9367ed8e2687e8b52f5d8de29798de4cc2860d1c70e91128dcbc515d8ca'
        linux_sha='e3f08054165be0a5e90779654b0e5c68d262ae794407d6347cdc6e8d05fafaaf'
        ;;
    '4.2.1')
        darwin_sha='967189ebadd6b65b1dd25464fdd4d2fcff7a00e0b776be425b19e283432d7862'
        linux_sha='35f398ad93af2b5eadd4b6b4fd4d4803b726029e572f40c4e1fe736db3de944b'
        ;;
    '5.0.0')
        darwin_sha='f7e8d1eac85ec125c430f9553e35d522c057895262956201ccea8a27d87054cc'
        linux_sha='42cfb37d2834d075996b9d02698674be7f322f0acd864b17c3191301329845f9'
        ;;
    *)
        echo "The requested Bazel version '$bazel_version' is not supported"
        exit 1
        ;;
esac

if [ -z "$bazel" ]; then
    bazel_bin_loc=~/.bazel_binaries
    mkdir -p $bazel_bin_loc
    bazel=$bazel_bin_loc/$bazel_version/bin/bazel-real
fi

if ! [ -f "$bazel" ]; then
    case $(uname -s) in
        Darwin)
            platform='darwin'
            sha=$darwin_sha
            ;;
        Linux)
            platform='linux'
            sha=$linux_sha
            ;;
        *)
            echo 'Your OS is not supported.'
            exit 1
            ;;
    esac
    remote_source=https://github.com/bazelbuild/bazel/releases/download
    installer_name="bazel-$bazel_version-installer-$platform-x86_64.sh"
    url="$remote_source/$bazel_version/$installer_name"
    (
        tmp_dir=$(mktemp -d)
        trap "rm -rf $tmp_dir" EXIT
        cd $tmp_dir
        (>&2 echo "downloading installer from")
        (>&2 echo "$url")
        curl -o installer.sh -L $url
        generated_sha=$(shasum -a 256 installer.sh | awk '{print $1}')
        if [ "$generated_sha" != "$sha" ]; then
            echo "Sha 256 does not match, expected: $sha"
            echo "But found $generated_sha"
            echo "Recommend you: update the sha to the expected"
            echo "and then re-run this script"
            exit 1
        fi
        chmod +x installer.sh
        ./installer.sh --base=$bazel_bin_loc/$bazel_version --bin=$bazel_bin_loc/$bazel_version/bin_t
    )
fi

extra_command_args=()

IFS=. read -r major minor patch < <(echo "$bazel_version")
extra_command_args+=("--config=v$major.$minor")

for (( i=1; i<=$#; i++ ))
do
    case "${!i}" in
        -*)
            ;;
        *)
            n=$(($i + 1))
            set -- "${@:1:$i}" "${extra_command_args[@]}" "${@:$n}"
            break
            ;;
    esac
done

disk_cache="$root_workspace"/.bazel_cache
mkdir -p "$disk_cache"

(>&2 echo :: exec "$bazel" "$@")
exec "$bazel" "$@"
