#!/bin/bash -e

abs_path() {
    perl -MCwd -le '
    for (@ARGV) {
      if ($p = Cwd::abs_path $_) {
        print $p;
      } else {
        warn "abs_path: $_: $!\n";
        $ret = 1;
      }
    }
    exit $ret' "$@"
}
workspace=$(cd $(dirname "$0")/..; pwd)
root_workspace=$(cd $(dirname $(abs_path "$0"))/..; pwd)

default_bazel_version='0.21.0'

if [ -z "$BAZEL_VERSION" ]; then
    bazel_version="$default_bazel_version"
else
    bazel_version="$BAZEL_VERSION"
fi

case "$bazel_version" in
    'host')
        bazel_version=$("$BAZEL_REAL" version | awk '/Build label/ {print $3}' | cut -d '-' -f 1)
        bazel="$BAZEL_REAL"
        ;;
    '0.21.0')
        darwin_sha='5e40dcf12a18990ffe5830fb5c83297aed090fd6e6c7c5b2eb720c19a33044fc'
        linux_sha='328d5fa87a61e1f6e674a8f88c5ae54b8987eaf5a6c944257600c5029c8feef8'
        ;;
    *)
        echo "The requested Bazel version '$bazel_version' is not supported"
        exit 1
        ;;
esac

if [ -z "$bazel" ]; then
    bazel_bin_loc=~/.bazel_binaries
    mkdir -p $bazel_bin_loc
    bazel=$bazel_bin_loc/$bazel_version/bin/bazel-real
fi

if ! [ -f "$bazel" ]; then
    case $(uname -s) in
        Darwin)
            platform='darwin'
            sha=$darwin_sha
            ;;
        Linux)
            platform='linux'
            sha=$linux_sha
            ;;
        *)
            echo 'Your OS is not supported.'
            exit 1
            ;;
    esac
    remote_source=https://github.com/bazelbuild/bazel/releases/download
    installer_name="bazel-$bazel_version-installer-$platform-x86_64.sh"
    url="$remote_source/$bazel_version/$installer_name"
    (
        tmp_dir=$(mktemp -d)
        trap "rm -rf $tmp_dir" EXIT
        cd $tmp_dir
        echo "downloading installer from"
        echo "$url"
        curl -o installer.sh -L $url
        generated_sha=$(shasum -a 256 installer.sh | awk '{print $1}')
        if [ "$generated_sha" != "$sha" ]; then
            echo "Sha 256 does not match, expected: $sha"
            echo "But found $generated_sha"
            echo "Recommend you: update the sha to the expected"
            echo "and then re-run this script"
            exit 1
        fi
        chmod +x installer.sh
        ./installer.sh --base=$bazel_bin_loc/$bazel_version --bin=$bazel_bin_loc/$bazel_version/bin_t
    )
fi

extra_command_args=()

if [ "$workspace" = "$root_workspace" ]; then
    extra_command_args+=("--config=rules")
fi

IFS=. read -r major minor patch < <(echo "$bazel_version")
if [ 0 -le "$major" ]; then
    if [ 21 -le "$minor" ]; then
        extra_command_args+=("--config=v0.21")
    fi
fi

for (( i=1; i<=$#; i++ ))
do
    case "${!i}" in
        -*)
            ;;
        *)
            n=$(($i + 1))
            (>&2 echo "${@:1:$n}")
            (>&2 echo $i $n)
            (>&2 echo "${@:$n}")
            set -- "${@:0:$n}" "${extra_command_args[@]}" "${@:$n}"
            break
            ;;
    esac
done

disk_cache="$root_workspace"/.bazel_cache
mkdir -p "$disk_cache"

(>&2 echo :: exec "$bazel" "$@")
exec "$bazel" "$@"
