load("//rules:build.bzl", "annex_scala_library")

scala = [
    "@scalas//:scala_2_12_0",
]

annex_scala_library(
    name = "foo",
    srcs = ["Foo.scala"],
    scala = scala,
    tags = ["manual"],
)
