load("@rules_scala_annex//rules:scala.bzl", "scala_binary")

scala = "@scala_2_11"

scala_binary(
    name = "one_discovered",
    srcs = ["one_discovered.scala"],
    scala = scala,
    tags = ["manual"],
)
