load("@rules_scala_annex//rules:build.bzl", "annex_scala_binary")

scala = "@scala_2_11"

annex_scala_binary(
    name = "one_discovered",
    srcs = ["one_discovered.scala"],
    scala = scala,
    tags = ["manual"],
)
