#!/bin/bash -e
. "$(dirname "$0")"/../../common.sh

bazel build :plain_java
diff <(sort expected_plain) <(
    zipinfo -m -T --h-t "$(bazel info bazel-bin)/resources/reference_conf/libplain_java.jar" | sort
)

bazel build :plain
diff <(sort expected_plain) <(
    zipinfo -m -T --h-t "$(bazel info bazel-bin)/resources/reference_conf/plain.jar" | sort
)
